"""Add language support to users and subscription plans

Revision ID: 741bea2a6221
Revises: 
Create Date: 2025-06-29 10:32:31.367917

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '741bea2a6221'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available_languages', sa.JSON(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_column('available_languages')

    # ### end Alembic commands ###
